export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const GET_USUARIOS = 'GET_USUARIOS';
export const GET_USUARIO = 'GET_USUARIO';

export const LOGOUT_USUARIO = 'LOGOUT_USUARIO';
export const LOGOUT_PAGE = 'LOGOUT_PAGE';
export const LOGOUT_PROJETO = 'LOGOUT_PROJETO';
export const LOGOUT_ATIVIDADE = 'LOGOUT_ATIVIDADE';
export const LOGOUT_CATEGORIA = 'LOGOUT_CATEGORIA';
export const LOGOUT_ADMINVIEW = 'LOGOUT_ADMINVIEW';


export const GET_CATEGORIA = 'GET_CATEGORIA';
export const GET_SUBCATEGORIA = 'GET_SUBCATEGORIA';
export const GET_DETALHARSUBCATEGORIA = 'GET_DETALHARSUBCATEGORIA';

export const GET_PROJETO = 'GET_PROJETO';
export const GET_DETALHARPROJETO = 'GET_DETALHARPROJETO';
export const GET_EDITARPROJETO = 'GET_EDITARPROJETO';

export const GET_ATIVIDADE = 'GET_ATIVIDADE';
export const GET_DETALHARATIVIDADE = 'GET_DETALHARATIVIDADE';
export const GET_EDITARATIVIDADE = 'GET_EDITARATIVIDADE';
export const GET_DETALHARCATEGORIA = 'GET_DETALHARCATEGORIA';

//PAGE ADMIN
export const PAGE_CADASTRO = 'PAGE_CADASTRO';
export const PAGE_LOGIN = 'PAGE_LOGIN';
export const PAGE_RECUPERAR = 'PAGE_RECUPERAR';
export const PAGE_ENVIAREMAIL = 'PAGE_ENVIAREMAIL';
export const PAGE_CADASTRO_CATEGORIA = 'PAGE_CADASTRO_CATEGORIA';
export const PAGE_CADASTRO_PROJETO = 'PAGE_CADASTRO_PROJETO';
export const PAGE_DETALHES_PROJETO = 'PAGE_DETALHES_PROJETO';
export const PAGE_EDITAR_PROJETO = 'PAGE_EDITAR_PROJETO';
export const PAGE_PROJETO = 'PAGE_PROJETO';
export const PAGE_CADASTRO_SUBCATEGORIA = 'PAGE_CADASTRO_SUBCATEGORIA';
export const PAGE_SUBCATEGORIA = 'PAGE_SUBCATEGORIA';
export const PAGE_USUARIO = 'PAGE_USUARIO';
export const PAGE_DASHBOARD = 'PAGE_DASHBOARD';
export const PAGE_EDITAR_SUBCATEGORIA = 'PAGE_EDITAR_SUBCATEGORIA';
export const PAGE_EDITAR_USUARIO = 'PAGE_EDITAR_USUARIO';
export const PAGE_DETALHAR_USUARIO = 'PAGE_DETALHAR_USUARIO';
export const PAGE_CATEGORIA = 'PAGE_CATEGORIA';
export const PAGE_EDITAR_CATEGORIA = 'PAGE_EDITAR_CATEGORIA';

//PAGE USUARIO
export const PAGE_CADASTRO_ATIVIDADE = 'PAGE_CADASTRO_ATIVIDADE';
export const PAGE_DETALHES_ATIVIDADE = 'PAGE_DETALHES_ATIVIDADE';
export const PAGE_EDITAR_ATIVIDADE = 'PAGE_EDITAR_ATIVIDADE';
export const PAGE_ATIVIDADE = 'PAGE_ATIVIDADE';